name: state_hub
description: Search a new aparment to life
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  bloc_concurrency: ^0.3.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.2.0
  go_router: ^16.2.4
  hydrated_bloc: ^10.1.1
  injectable: ^2.5.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  very_good_infinite_list: ^0.9.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.1.0
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
